# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- None 

variables:
- group: 'DBPasses'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(build.sourcesdirectory)/env'
        backendServiceArm: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'
        backendAzureRmResourceGroupName: 'NextOps'
        backendAzureRmStorageAccountName: 'nextopstfsa01'
        backendAzureRmContainerName: 'terraform'
        backendAzureRmKey: 'DEV/dev.tfstate'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(build.sourcesdirectory)/env'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'    
    - task: MysqlDeploymentOnMachineGroup@1
      inputs:
        TaskNameSelector: 'SqlTaskFile'
        SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/schema.sql'
        ServerName: 'nextopsmysql-dev01.mysql.database.azure.com'
        DatabaseName: 'petclinic'
        SqlUsername: 'petclinic@nextopsmysql-dev01'
        SqlPassword: $(DBDevPass)
    - task: MysqlDeploymentOnMachineGroup@1
      inputs:
        TaskNameSelector: 'SqlTaskFile'
        SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/data.sql'
        ServerName: 'nextopsmysql-dev01.mysql.database.azure.com'
        DatabaseName: 'petclinic'
        SqlUsername: 'petclinic@nextopsmysql-dev01'
        SqlPassword: $(DBDevPass)
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-Ddb.script=mysql -Djpa.database=MYSQL -Djdbc.driverClassName=com.mysql.cj.jdbc.Driver -Djdbc.url=jdbc:mysql://nextopsmysql-dev01.mysql.database.azure.com:3306/petclinic?useUnicode=true -Djdbc.username=petclinic@nextopsmysql-dev01 -Djdbc.password=$(DBDevPass)'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)/dev
    
    - task: MysqlDeploymentOnMachineGroup@1
      inputs:
        TaskNameSelector: 'SqlTaskFile'
        SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/schema.sql'
        ServerName: 'nextopsmysql-staging01.mysql.database.azure.com'
        DatabaseName: 'petclinic'
        SqlUsername: 'petclinic@nextopsmysql-staging01'
        SqlPassword: $(DBStagePass)
    - task: MysqlDeploymentOnMachineGroup@1
      inputs:
        TaskNameSelector: 'SqlTaskFile'
        SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/data.sql'
        ServerName: 'nextopsmysql-staging01.mysql.database.azure.com'
        DatabaseName: 'petclinic'
        SqlUsername: 'petclinic@nextopsmysql-staging01'
        SqlPassword: $(DBStagePass)    
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-Ddb.script=mysql -Djpa.database=MYSQL -Djdbc.driverClassName=com.mysql.cj.jdbc.Driver -Djdbc.url=jdbc:mysql://nextopsmysql-staging01.mysql.database.azure.com:3306/petclinic?useUnicode=true -Djdbc.username=petclinic@nextopsmysql-staging01 -Djdbc.password=$(DBStagePass)'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)/stage

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy Dev
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxDevWebApp
    displayName: Deploy Linux Dev Web App
    environment: $(devenvironmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: nextopsapp-dev-01'
            inputs:
              azureSubscription: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'
              appType: 'webAppLinux'
              appName: '$(devwebAppName)'
              package: '$(Pipeline.Workspace)/drop/dev/target/*.?(war|jar)'
              runtimeStack: 'TOMCAT|8.5-jre8'

- stage: Deploy1
  displayName: Deploy stage
  dependsOn: Deploy
  condition: succeeded()
  jobs: 
  - deployment: DeployLinuxStageWebApp
    displayName: Deploy Linux Stage Web App
    environment: $(stageenvironmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: nextopsapp-staging-01'
            inputs:
              azureSubscription: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'
              appType: 'webAppLinux'
              appName: '$(stagewebAppName)'
              package: '$(Pipeline.Workspace)/drop/stage/target/*.?(war|jar)'
              runtimeStack: 'TOMCAT|8.5-jre8'