# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
   exclude:
     - main
  paths:
   include:
     - '**/src' 

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '**/src'

schedules:
  - cron: "30 17 * * *"

variables:
  # Web app name
  webAppName: 'nextopswa11'

  # Environment name
  environmentName: 'nextopswa11'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'Artifacts01_Feed'
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false    
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'deploy'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/env'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/src/main/resources/db/mysql'
        Contents: '*.sql'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

    - task: DownloadPackage@1
      inputs:
        packageType: 'maven'
        feed: '396fa978-a0c4-47cc-bad2-6da94523f588/118b96a5-45d2-4a1e-996f-aa06484c8181'
        view: 'a493b978-d22d-45be-848c-22f2a3579307'
        definition: '2e26df78-1d65-4e67-a79f-b14466854819'
        version: '5.3.22'
        downloadPath: '$(System.ArtifactsDirectory)'