# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- None

variables:
  # Web app name
  webAppName: 'nextopswa11'
  DBName : 'nextopsmysql11'

  # Environment name
  environmentName: 'nextopswa11'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(build.sourcesdirectory)/env'
        backendServiceArm: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'
        backendAzureRmResourceGroupName: 'NextOps'
        backendAzureRmStorageAccountName: 'nextopstfsa01'
        backendAzureRmContainerName: 'terraform'
        backendAzureRmKey: 'DEV/dev.tfstate'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(build.sourcesdirectory)/env'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Pay-As-You-Go (a355c32e-4a22-4b05-aab4-be236850fa6e)'    
    - task: MysqlDeploymentOnMachineGroup@1
      inputs:
        TaskNameSelector: 'SqlTaskFile'
        SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/schema.sql'
        ServerName: 'nextopsmysql11.mysql.database.azure.com'
        DatabaseName: 'petclinic'
        SqlUsername: 'petclinic@nextopsmysql11'
        SqlPassword: 'Admin@12345678'
    - task: MysqlDeploymentOnMachineGroup@1
      inputs:
        TaskNameSelector: 'SqlTaskFile'
        SqlFile: '$(build.sourcesdirectory)/src/main/resources/db/mysql/data.sql'
        ServerName: 'nextopsmysql11.mysql.database.azure.com'
        DatabaseName: 'petclinic'
        SqlUsername: 'petclinic@nextopsmysql11'
        SqlPassword: 'Admin@12345678'
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-Ddb.script=mysql -Djpa.database=MYSQL -Djdbc.driverClassName=com.mysql.cj.jdbc.Driver -Djdbc.url=jdbc:mysql://nextopsmysql11.mysql.database.azure.com:3306/petclinic?useUnicode=true -Djdbc.username=petclinic@nextopsmysql11 -Djdbc.password=Admin@12345678'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)/dev

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: nextopswa11'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/dev/target/*.?(war|jar)'