# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- None

variables:
  # Web app name
  webAppName: 'nextopswa11'

  # Environment name
  environmentName: 'nextopswa11'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'Artifacts01_Feed'
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/env'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/src/main/resources/db/mysql'
        Contents: '*.sql'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

